Play travis
Otus-DevOps-2022-02/M1kH61l_infra pull request #1
Opened 2022-03-27 06:07 UTC by M1kH61l

2022-03-28 14:46 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Нужно пофиксить тесты, к сожалению они у вас не проходят
Оставил комментарии к файлам на которые стоит обратить вниманием
Так же не забывайте оставлять описание к вашим пуллреквестам
ДЗ возвращаю на доработку

2022-03-28 14:46 UTC, mrgreyves commented on play-travis/test_2.py
> +import unittest
Вот этот файлик лишний, его стоит удалить =)

2022-03-28 14:46 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
А вот тут есть над чем поработать =)

2022-03-31 18:20 UTC, M1kH61l commented
Поправил ошибки, просьба проверить домашнее задание.

2022-04-01 09:32 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь апрув =)

2022-04-01 18:29 UTC, merged