Terraform 1
Otus-DevOps-2022-02/M1kH61l_infra pull request #4
Opened 2022-04-22 11:27 UTC by M1kH61l

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2022-04-25 08:13 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Не хватает достаточно большого количества файлов
Нужно свериться с результатми тестов
ДЗ возвращаю на доработку

2022-04-27 06:04 UTC, M1kH61l commented
поправил не корректные регистры в папке Packer и ошибки в именах недостающих файлах.

2022-05-01 14:27 UTC, M1kH61l commented
Поправил ошибки по ДЗ. просьба проверить

2022-05-02 11:58 UTC, mrgreyves requested changes
Здравствуйте!)
Надо еще чуть-чуть подправить, что бы ошибки не лезли дальше
Не хватает фейкового ключика для пакера

2022-05-08 10:33 UTC, M1kH61l commented
Просьба проверить

2022-05-10 10:21 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-05-10 10:31 UTC, merged